services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: sca_jp
      POSTGRES_PASSWORD: Panda23
      POSTGRES_DB: arcadia_auth
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
